### ISSUE TITLE
[Feature] Take's arguments from cli

### ISSUE THREAD

**Issue by arbazkiraak** [UltimateHackers/XSStrike#7]
Hey @UltimateHackers ,

Thanks for Creating this tool.

i Have a Feature request , It Would be good for more automation . !

How about passing params directly :

python xssstrike.py  -get -u URLHERE  -level=LEVELNUMBER

whereas:
LEVELNUMBER =  1 = Fuzzer
LEVELNUMBER =  2 = Striker
LEVELNUMBER =  3 = Spider

------------------------------------------------------

Need output functionality to store all log or result : 
ex:
python xssstrike.py  -get -u https://google.com?x=xxx  -level=2  -o test.log

--------------------------------------------------------

I'm Looking forward to contribute to this project  and help to add this above 2 features :)

**Comment by UltimateHackers** [comment]
Thanks for the suggestion but I personally feel that using cli arguments will cause a bad user experience.
With the current variant, you just enter the URL, press enter to skip the cookie thing and then choose the desired option. It seems more user friendly to me.
But we can add the log feature for sure..
Regards!

**Comment by arbazkiraak** [comment]
@UltimateHackers  :)  I Agree it will cause bad user experience . but I Request you to just keep it 2 ways .

1. python xssstrike.py -cli      (-cli = argument should be 1st way to pass arguments directly from cli)
ex: python xssstrike.py -cli -url -get -u https://google.com?x=xxx -level=2 -o test.log

2. python xssstrike  ( 2nd way is user friendly , current one)

**Comment by arbazkiraak** [comment]
For now just implement this above feature  for GET REQUEST ONLY  :)
ex: python xssstrike.py -cli -url -get -u https://google.com?x=xxx  -cookie=file.txt -level=2 -o test.log

Will see later about POST Request with data params from cli arguments

**Comment by arbazkiraak** [comment]
Closing :  Not Necessary feature

**Comment by ekrem0** [comment]
@arbazkiraak your issue was essential.
cli arguments play a very important role in cli tools , real hackers actually do not care about the fancy user interface (colors are okay though) but they prefer arguments (its much simple and easier) than childish input. ( Who the hell even design this tool , it looks childish)

and seriously @UltimateHackers you really need to refactor your code base it uses python2.7 and 
mechanize ( that is gonna hurt so much things ). no offense but you need to learn the standards
and there is no discipline in the source code , I dont even get anything from **head to toe** .

Lads you are seriously are childish , no offense just telling you the truth +Star and +Fork for your hard
work of 1095 lines of code (?).
